/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BelepesRouteImport } from './routes/belepes'
import { Route as ArakRouteImport } from './routes/arak'
import { Route as IndexRouteImport } from './routes/index'

const BelepesRoute = BelepesRouteImport.update({
  id: '/belepes',
  path: '/belepes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArakRoute = ArakRouteImport.update({
  id: '/arak',
  path: '/arak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arak': typeof ArakRoute
  '/belepes': typeof BelepesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arak': typeof ArakRoute
  '/belepes': typeof BelepesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arak': typeof ArakRoute
  '/belepes': typeof BelepesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arak' | '/belepes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arak' | '/belepes'
  id: '__root__' | '/' | '/arak' | '/belepes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArakRoute: typeof ArakRoute
  BelepesRoute: typeof BelepesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/belepes': {
      id: '/belepes'
      path: '/belepes'
      fullPath: '/belepes'
      preLoaderRoute: typeof BelepesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arak': {
      id: '/arak'
      path: '/arak'
      fullPath: '/arak'
      preLoaderRoute: typeof ArakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArakRoute: ArakRoute,
  BelepesRoute: BelepesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
